include: package:lints/recommended.yaml

formatter:
  page_width: 120

linter:
  rules:
    - prefer_single_quotes
    - sort_constructors_first
    - unawaited_futures
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_locals
